#   README:
#   You need to use
#   docker network create --subnet=172.18.0.0/16 bacula_network
#   before being able to use this docker compose

#   Still Need to look into the 
#   build: ./directory_to_build
#   thing 

version: '2'


services:
<<<<<<< HEAD
  database:
    image: postgres:latest
    container_name: bacula-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

  director:
    build:
      context: ./docker/mydirector
      dockerfile: ./Dockerfile
    image: bacula/director
    container_name: bacula-dir
    hostname: bacula-dir
    #tty: true
    #stdin_open: true
    #env_file: .env
    environment:
      DIRPASS: ${DIRPASS}
      FDPASS: ${FDPASS}
      SDPASS: ${SDPASS}
      DIRADDR: ${DIRADDR}
      FDADDR: ${FDADDR}
      SDADDR: ${SDADDR}
      DBADDR: ${DBADDR}
      FDRESTOREDIR: ${FDRESTOREDIR}
      FDBACKUPDIR: ${FDBACKUPDIR}  
    expose:
      - 9101

  bacula-fd:
    build:
      context: ./docker/myfiledaemon
      dockerfile: ./Dockerfile
    image: bacula/filedaemon
    container_name: bacula-fd
    hostname: bacula-fd
    tty: true
    #env_file: .env
    environment:
      FDPASS: ${FDPASS}
      FDADDR: ${FDADDR}
      FDRESTOREDIR: ${FDRESTOREDIR}
      FDBACKUPDIR: ${FDBACKUPDIR}
    volumes: 
      #check if you need :ro
      #directories
      - ./volumes/backup/:/home/backup/
      - ./volumes/restore/:/home/restore/
    expose:
      - 9102
=======
    bacula-dir:
        build:
            context: ./mydirector
            dockerfile: ./Dockerfile
        image: bacula/director
        tty: true
        container_name: bacula-dir
        hostname: bacula-dir
        #env_file: .env
        environment:
            DIRPASS: ${DIRPASS}
            FDPASS: ${FDPASS}
            SDPASS: ${SDPASS}
            DIRADDR: ${DIRADDR}
            FDADDR: ${FDADDR}
            SDADDR: ${SDADDR}
            FDRESTOREDIR: ${FDRESTOREDIR}
            FDBACKUPDIR: ${FDBACKUPDIR}
        
        #ports:
        #    - "9101:9101"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.11

    bacula-fd:
        build:
            context: ./myfiledaemon
            dockerfile: ./Dockerfile
        image: bacula/filedaemon
        tty: true
        container_name: bacula-fd
        hostname: bacula-fd
        #env_file: .env
        environment:
            FDPASS: ${FDPASS}
            FDADDR: ${FDADDR}
            FDRESTOREDIR: ${FDRESTOREDIR}
            FDBACKUPDIR: ${FDBACKUPDIR}
        volumes: 
            #check if you need :ro
           
            #directories
            - ./volumes/backup/:/home/backup/
            - ./volumes/restore/:/home/restore/
        
        # ports:
        #     - "9102:9102"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.12

    bacula-sd:
        build:
            context: ./mystoragedaemon
            dockerfile: ./Dockerfile
        image: bacula/storagedaemon
        tty: true
        container_name: bacula-sd
        hostname: bacula-sd
        #env_file: .env
        environment:
            SDPASS: ${SDPASS}
            SDADDR: ${SDADDR}
            SDDIR: ${SDDIR}
        volumes: 
            #check if you need :ro
       
            #directories
            - ./volumes/storage/:/home/
            
        # ports:
        #     - "9103:9103"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.13
>>>>>>> df164e46e328bec9d3df01deae0f8f77bbb0db35

  bacula-sd:
    build:
      context: ./docker/mystoragedaemon
      dockerfile: ./Dockerfile
    image: bacula/storagedaemon
    container_name: bacula-sd
    tty: true
    hostname: bacula-sd
    #env_file: .env
    environment:
      SDPASS: ${SDPASS}
      SDADDR: ${SDADDR}
      SDDIR: ${SDDIR}
    volumes: 
      #check if you need :ro
      #directories
      - ./volumes/storage/:/home/
    expose:
      - 9103
