#   README:
#   You need to use
#   docker network create --subnet=172.18.0.0/16 bacula_network
#   before being able to use this docker compose

#   Still Need to look into the 
#   build: ./directory_to_build
#   thing 

version: '2'


services:
    bacula-dir:
        build:
            context: ./mydirector
            dockerfile: ./Dockerfile
            image: bacula/director
        tty: true
        container_name: bacula-dir
        hostname: bacula-dir
        #env_file: .env
        environment:
            DIRPASS: ${DIRPASS}
            FDPASS: ${FDPASS}
            SDPASS: ${SDPASS}
            DIRADDR: ${DIRADDR}
            FDADDR: ${FDADDR}
            SDADDR: ${SDADDR}
            FDRESTOREDIR: ${FDRESTOREDIR}
            FDBACKUPDIR: ${FDBACKUPDIR}
        
        #ports:
        #    - "9101:9101"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.11

    bacula-fd:
        build:
            context: ./myfiledaemon
            dockerfile: ./Dockerfile
            image: bacula/filedaemon
        tty: true
        container_name: bacula-fd
        hostname: bacula-fd
        #env_file: .env
        environment:
            FDPASS: ${FDPASS}
            FDADDR: ${FDADDR}
            FDRESTOREDIR: ${FDRESTOREDIR}
            FDBACKUPDIR: ${FDBACKUPDIR}
        volumes: 
            #check if you need :ro
           
            #directories
            - ./volumes/backup/:/home/backup/
            - ./volumes/restore/:/home/restore/
        
        # ports:
        #     - "9102:9102"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.12

    bacula-sd:
        build:
            context: ./mystoragedaemon
            dockerfile: ./Dockerfile
            image: bacula/storagedaemon
        tty: true
        container_name: bacula-sd
        hostname: bacula-sd
        #env_file: .env
        environment:
            SDPASS: ${SDPASS}
            SDADDR: ${SDADDR}
            SDDIR: ${SDDIR}
        volumes: 
            #check if you need :ro
       
            #directories
            - ./volumes/storage/:/home/
            
        # ports:
        #     - "9103:9103"
        networks:
            bacula_network:
                ipv4_address: 172.18.0.13

#NETWORK DEFINITION
networks:
  bacula_network:
    external: true
